### ISSUE TITLE
Standard_Token total supply

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/Tokens#10]
Standard_Token declares `totalSupply` var but does not implement `totalSupply()`

not sure if this is intentional or not

**Comment by simondlr** [comment]
It's a public variable, so a getter function is automatically created for it. One could technically collapse balanceOf & allowance into only public variables as well (without creating a separate function as it is now).

**Comment by MrChico** [comment]
I am for making balanceOf & allowance into public mappings instead. Also, I would declare the variables at the top of the contract, but that is just my preference.

**Comment by simondlr** [comment]
@MrChico I wonder if there is any extra gas overhead to doing either. Will run some experiments. :)

**Comment by kumavis** [comment]
Thanks
