### ISSUE TITLE
Problem with a error and compiler version

### ISSUE THREAD

**Issue by rvmvmvm** [ConsenSys/Tokens#136]
Does anybody know how to fix the following error?:
![captura](https://user-images.githubusercontent.com/39865867/40881071-eb32ba00-66bd-11e8-8743-027d1c768d75.PNG)

**Comment by maurelian** [comment]
I think you might be using an older version of the compiler that doesn't understand the emit kw. Try using a newer version. You might need to update the other contracts to get them all to the same compiler version compatibility.
