### ISSUE TITLE
Checking balance should not require hex prefix

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/Tokens#30]
Right now entering a non-hex-prefixed address into the `check balance` field will silently fail to the user.

It would be easy enough to call `ethUtil.addHexPrefix(userInput)`, so I think that would be better.

**Comment by simondlr** [comment]
This is related to the Token Factory, right? I'll move the issue to that repo. Just want to confirm. :)

**Comment by flyswatter** [comment]
Yes, sorry, I thought this was the tokenfactory repo.

- Dan

**Comment by simondlr** [comment]
No worries! Added to Token Factory issues. Thanks!
