### ISSUE TITLE
Are these importable by some means?

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/Tokens#31]
Are these registered on a solidity package manager, like Dapple, to allow easy installing in a project?

I even think npm registration could work, if you clarified in the readme what importing entailed.

Any thoughts about ways these should be consumed?

**Comment by simondlr** [comment]
Not yet. Just go ahead and copy/paste the token code you require. Anything that's not clear? Perhaps we can update the documentation to make it more clear. :)

**Comment by simondlr** [comment]
It's now on ethpm. v0.0.2 coming soon with 0.4.8 Solidity support. :)

Published under 'tokens'.
