### ISSUE TITLE
Transaction fail

### ISSUE THREAD

**Issue by bingo123** [ConsenSys/Tokens#34]
I try to implement HumanStandardToken.sol on the develoment environment of an ethereum - wallet and i get: It seems this transaction will fail. If you submit it will consume all the gas you sent.

![unbenannt 2jpg](https://cloud.githubusercontent.com/assets/6627278/20278155/e1c6f8a0-aaa3-11e6-8315-937c4e9f1127.JPG)

[code.txt](https://github.com/ConsenSys/Tokens/files/590198/code.txt)

**Comment by simondlr** [comment]
Hi. Is there any other information you can share? What version of Mist are you using? What's the error results? Can you potentially deploy to Morden and get the tx hash so that one can see the result on etherscan?

**Comment by bingo123** [comment]
Hi i am using Ethereum Wallet o.7.8. and i have a parity im geth Mode underneath syncing. I will try to do deploy to Morden and let you know the tx Hash.

**Comment by simondlr** [comment]
If there was still an issue, let us know.
