### ISSUE TITLE
Why is approve returning bool?

### ISSUE THREAD

**Issue by Georgi87** [ConsenSys/Tokens#35]
The approve function can only return true, why does it return anything?
```
   function approve(address _spender, uint256 _value)
        public
        returns (bool)
    {
        allowed[msg.sender][_spender] = _value;
        Approval(msg.sender, _spender, _value);
        return true;
    }
```
I would propose to change it to:
```
   function approve(address _spender, uint256 _value)
        public
    {
        allowed[msg.sender][_spender] = _value;
        Approval(msg.sender, _spender, _value);
    }
```

**Comment by simondlr** [comment]
approve() in ERC20 requires returning a bool.

In this implementation, it's just always true.

**Comment by ethers** [comment]
Yes, ERC20 is just an interface.
There could be an ERC20 token that for example, forbids approval for certain addresses, such as the 0 address.

**Comment by Georgi87** [comment]
Ok, thanks for explaining. Closing this :)
