### ISSUE TITLE
Interact with Token on localhost using testrpc, Metamask, and truffle

### ISSUE THREAD

**Issue by Canalytic** [ConsenSys/Tokens#38]
I've been using truffle to deploy contracts via a localhost, and using metamask to interact with the dapp.  I am wondering if I can load that contract for this token into tokenfactory?  When I access the tokenfactory website I can't use it unless I have metamask installed.  So, Im just assuming that if I have metamask connected to a private network then any way I interact with token factory will also be on localhost (a side note is if I am not on local host then do I have to pay the gas fee to create the tokens over the mainnet?)

When I try to interact with a token (for example using the metacoin.sol test token from truffle)  I use the metacoin address provided after running `truffle serve`.  The procedure brings up:

> Interacting with token at address: 0x0ef790110aa9fded64c8dff1d8d96be05c8a5024. 
Total Supply is: . 

How can I interact with this token I created and served using truffle using the token factory interface?  Am I missing something like not adding the correct contract address?

**Comment by simondlr** [comment]
If you are connected to testrpc from Metamask, the token deployed through truffle, you should be able to interact with, through Token Factory.

However, metacoin.sol in the Truffle example is not ERC20-compliant and won't work in Token Factory. cc @tcoulter.

**Comment by simondlr** [comment]
Hey @Canalytic! iirc, your issue was that metacoin wasn't compliant with ERC20. Can I close this? :)

**Comment by Canalytic** [comment]
Yes, please
