### ISSUE TITLE
The contract deployment failed: Contract not deployed, getCode returned 0x

### ISSUE THREAD

**Issue by mattvick** [ConsenSys/Tokens#48]
Deploying the HumanStandardTokenFactory contract fails with the error `Contract not deployed, getCode returned 0x`.

![screen shot 2017-05-08 at 11 15 42 am](https://cloud.githubusercontent.com/assets/651430/25800097/2e5edbce-33e8-11e7-93f8-d80703c757dc.png)

Deploying to the Kovan network using Parity

**Comment by mattvick** [comment]
I've "fixed" this by removing the verification parts of the code:
https://github.com/mattvick/Tokens/commit/3122b61ec7302d19ad2ff32a907f8b7dd810116e

I've also added a `ContractInstantiation` event:
https://github.com/mattvick/Tokens/commit/42ec083c03f39dafc72203088b275e1336cf957f

**Comment by ethers** [comment]
Hi, did you try passing more gas?  The factory may need more gas (but I don't know why).
