### ISSUE TITLE
Truffle migration failed

### ISSUE THREAD

**Issue by ChenhaoXu304** [ConsenSys/Tokens#50]
When running "truffle migrate", the following error is returned:
"Error: Could not find built Migrations contract: Could not find artifacts for ./Migrations.sol from any sources."

I cloned from this repository and built with "npm install". Did I miss any steps in building? 

Truffle version: 3.2.4
OS: Windows 10

**Comment by simondlr** [comment]
Ah yes. @ChenhaoXu304, Migrations aren't in this installation. We haven't used the contract to directly deploy it from this Truffle repo. It's recommended that you pull the contracts into your own projects and build your migrations from there (if it makes sense).

**Comment by simondlr** [comment]
This was fixed in a recent PR. Thanks for brining it up.
