### ISSUE TITLE
Many similarities with official Ethereum website - which one to choose?

### ISSUE THREAD

**Issue by stefek99** [ConsenSys/Tokens#51]
Your contract: https://github.com/ConsenSys/Tokens/tree/master/Token_Contracts/contracts

Contract on Ethereum website: https://www.ethereum.org/token

Both are implementing ERC20 interface, I was just wondering maybe it's a good idea to have all different implementations in a single place for completeness...

**Comment by stefek99** [comment]
Also here - many "industry standard" contracts: https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/contracts

**Comment by simondlr** [comment]
There are various implementations indeed. Zeppelin and Mini-me are excellent, well-tested alternatives.

**Comment by stefek99** [comment]
@simondlr thank you for suggestion.

I've actually posted question here: https://ethereum.stackexchange.com/questions/21548/where-to-find-ico-contract-with-linear-logarithmic-decrease

(maybe you'll know)
