### ISSUE TITLE
Throw on failed transfer?

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/Tokens#61]
Hey @skmgoldin. Seems like consensus is that we should throw when not having enough balance (vs return false).

https://github.com/ethereum/EIPs/pull/610/files

Never fully liked this. It's a trade-off in its own right, but if the community is moving to this, do we want to change to this?

**Comment by skmgoldin** [comment]
I think it's a great idea if by `throw` they mean `revert`. Those will be catchable errors in Metro. I think they must mean this, let me ask in the EIP.

**Comment by skmgoldin** [comment]
I think they must mean `revert` because `throw` is actually deprecated in Solidity now.

**Comment by simondlr** [comment]
Yes, I assume it's revert as well.

**Comment by skmgoldin** [comment]
I'll work on a PR.
