### ISSUE TITLE
Update test suite to async/await

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/Tokens#64]
Async await syntax is much more readable, which is useful for reviewability.

**Comment by skmgoldin** [comment]
Anyone want to take this on?

**Comment by maurelian** [comment]
yeah, I'm interested in doing this. Please assign it to me @skmgoldin 

I think I can fit it in during my morning pre-work "learning" slot.  If not, I'll update here.

**Comment by Janaka-Steph** [comment]
Hello @skmgoldin @maurelian 

I agree async/await is much more readable, I rewrote them so here is a PR https://github.com/ConsenSys/Tokens/pull/70

**Comment by skmgoldin** [comment]
Thanks @Janaka-Steph, I'll review.

**Comment by maurelian** [comment]
Under review and editing at #71

**Comment by Janaka-Steph** [comment]
@maurelian I noticed that you reverted my commit b143e19, even when my work have been merged. Can you explain me why?

**Comment by maurelian** [comment]
completed by #71
