### ISSUE TITLE
Over Gas Limit

### ISSUE THREAD

**Issue by Remi-Tuy** [ConsenSys/Tokens#69]
I have been trying to execute the HumanStandardTokenFactory using Remix & MetaMask on a custom chain.

I keep getting the following message:
`callback contain no result Gas required exceeds block gas limit: 800000000`

![capture](https://user-images.githubusercontent.com/30529561/29272263-2bf14bc2-80f7-11e7-9e95-44ba5b9fadf4.PNG)

It does say in the comments of the contract that the function  'verifyHumanStandardToken' can cost about 800k gas, therefore my transaction gas limit should be enough. 
I have checked my custom chain gas limit in the genesis block and it is 4712388:

`eth.getBlock("latest").gasLimit
4712388
`

I have not modified the template code at all, so what am I missing ?

**Comment by Remi-Tuy** [comment]
Updated my issue with a exemple

**Comment by simondlr** [comment]
Still not sure what's the issue unless the code deployment is actually >4.7m gas. If you run tests with gasLimit on testrpc set at 4.7m gas that might help understand. Tests are passing.

**Comment by maurelian** [comment]
This issue is stale. Closing.
