### ISSUE TITLE
Add throw on fallback function to StandardToken.sol?

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/Tokens#7]
@alexvandesande standard token has the fallback function implement a throw(), implying that whenever Ether is sent to it, it automatically reverts. This causes the possibility for Ether to get locked up in the contract to not happen. 

See here: https://gist.github.com/alexvandesande/0d1a998d949e26942212

Question: Should this be in this repo's current standard token code? Only reason why I feel this should not be the case is that one could create an etherbank contract to extend token functionality to Ether itself. But then would be a substantially different one as well.

So gut feel, yes. Add it in.

**Comment by MrChico** [comment]
I also think it would be a good idea to have it by default, because I can see how users might mix things up and accidentally send a transaction with a value instead of calling the transfer.
So best case scenario it saves somebody's day, worst case it adds a minuscule gas cost to the contract

**Comment by ethers** [comment]
Good to add throw on fallback function.  (Seems maybe Solidity should have this as a default and contracts can override: those that explicitly want Ether and have ways so that the Ether isn't locked up).

**Comment by alexvandesande** [comment]
It's a very important security measure in my opinion. You can always override it with something else, e.g. forward any ether sent to it to another address.

**Comment by simondlr** [comment]
Yeah. Agreed. I've started adding it, but ran into problems with the test. Should have it done soon. :)

**Comment by simondlr** [comment]
Added in. Wanted to do a more proper test, but estimateGas wasn't behaving like I thought it would (it would be nice if it gave gas costs in the event of exceptions).
