### ISSUE TITLE
eslint config?

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/Tokens#73]
@skmgoldin I see you [added some eslint plugins](https://github.com/ConsenSys/Tokens/blame/07d2590e43e1514ccd428bfe5b37ef4537bde02a/package.json#L33-L36). Do you have a config file for it? 

Should we add eslint as a dependency as well, or is best practice to run a global install?

**Comment by skmgoldin** [comment]
Good catch we should install `eslint` itself in the devDependencies. I'll look into this.

**Comment by maurelian** [comment]
Looks like it may have been eslint's standard rules: https://github.com/ConsenSys/Tokens/blame/59e92af4a290e0d7945084e78daa4a57cecffe9b/package.json#L36
