### ISSUE TITLE
Review and clean up code comments

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/Tokens#74]
For example, what does this mean? 

https://github.com/ConsenSys/Tokens/pull/71/files#diff-d44cc2e3f0ad5591d79d9df53837e60fR37

**Comment by skmgoldin** [comment]
I agree this repo may actually be _over_commented in some areas.

**Comment by maurelian** [comment]
Definitely. As I look through it, this repo feels like it's by ConsenSys devs, for ConsenSys devs. There's a lot of low hanging fruit for making this more reusable.
