### ISSUE TITLE
Clean up JS tests

### ISSUE THREAD

**Issue by kfichter** [ConsenSys/Tokens#88]
I think the JS unit tests need to be cleaned up. I've been working on it a little bit, I'll submit a pull request if I get positive feedback. [Subsections](https://github.com/ConsenSys/Tokens/blob/master/test/humanStandardToken.js#L12) should probably be split by a `describe` clause. [Assertion style](https://github.com/ConsenSys/Tokens/blob/master/test/humanStandardToken.js#L33) should probably also be standardized for readability. Comments don't make much sense inside the tests unless describing some obscure bug (unit tests should be relatively self explanatory). Thoughts?

**Comment by maurelian** [comment]
@kfichter yes agree, and this would be very much appreciated. 

If you're going in there, I also very much dislike the pattern of initiating a new contract for each test.
In fact, I would like it if the test suite could be also be use to test a contract already deployed at any address with some small tweaks.

**Comment by kfichter** [comment]
@maurelian awesome, I'll go ahead and clean some more things up and submit pull reqs when I'm done!
