### ISSUE TITLE
OOG on codeship test

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/Tokens#89]
![image](https://user-images.githubusercontent.com/23033765/32625674-df9abdf0-c55a-11e7-8c7e-21c7b60759df.png)

I'm not sure how this is configured, but codeship's testrpc will need to increase the gas. 

@skmgoldin Maybe it's time to get this moved to not your personal codeship account?

**Comment by kfichter** [comment]
Easiest fix for now would be to add `--gasLimit 6800000` as testrpc arguments
